const countryCityData = {
    Argentina: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata"],
    Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
    Austria: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
    Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
    Belgium: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège"],
    Brazil: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza"],
    Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
    Chile: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
    China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu"],
    Colombia: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
    Czech: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"],
    Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
    Egypt: ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
    Finland: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
    France: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
    Germany: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Stuttgart"],
    Greece: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
    Hungary: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
    India: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
    Indonesia: ["Jakarta", "Surabaya", "Bandung", "Bekasi", "Medan"],
    Ireland: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
    Israel: ["Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva"],
    Italy: ["Rome", "Milan", "Naples", "Turin", "Palermo"],
    Japan: ["Tokyo", "Osaka", "Kyoto", "Nagoya", "Sapporo"],
    Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
    Malaysia: ["Kuala Lumpur", "George Town", "Ipoh", "Johor Bahru", "Kota Kinabalu"],
    Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
    Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
    New_Zealand: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
    Nigeria: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt"],
    Norway: ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen"],
    Pakistan: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Peshawar"],
    Peru: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Iquitos"],
    Poland: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań"],
    Portugal: ["Lisbon", "Porto", "Amadora", "Braga", "Coimbra"],
    Russia: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
    Saudi_Arabia: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
    Singapore: ["Singapore"],
    South_Africa: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
    South_Korea: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
    Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"],
    Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
    Switzerland: ["Zurich", "Geneva", "Basel", "Lausanne", "Bern"],
    Thailand: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Hat Yai"],
    Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
    UAE: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
    UK: ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool"],
    USA: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    Venezuela: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
};

export default countryCityData